### ISSUE TITLE
Correctly select the result

### ISSUE THREAD

**Issue by Hugz59** [MPCodeWriter21/whois21#4]
Hey, 

I would like to use your package for my tool but i don't know who to have a good display of the result. 

In my tool, when i call your function, i have this : 

![whois](https://github.com/MPCodeWriter21/whois21/assets/40318765/b456b0c7-4789-4dc7-848c-f7e994de7003)

I would like each result to have its own line so that it is clearer but impossible to do. 

I want a result like this : 

![whoisbg](https://github.com/MPCodeWriter21/whois21/assets/40318765/66903df4-e36b-424e-96c7-cabd626dbf13)

This is my code : 

```
domain_whois = whois21.WHOIS(domain_name)

return render(request, 'toolbox/whois.html', {'whois' : domain_whois})
```

I'm using Django for my tool. 

Any idea ? 

Thx !

**Comment by MPCodeWriter21** [comment]
Hi there!

It looks like you put the raw data directly into your html data and the whitespaces in the data were trimmed. You could put the raw data in special tags such as `pre` and `textarea` that treat whitespaces differently.
![textarea](https://github.com/MPCodeWriter21/whois21/assets/67067607/9715badc-da97-4d99-8ef9-e0d5f8956e77)
![pre](https://github.com/MPCodeWriter21/whois21/assets/67067607/83025a6e-1245-4d31-ab1e-a8b352e56fc2)


You can also try replacing `'\n'` with `'<br>'` in the raw data.

But if you want the specific information you mentioned in the second image, You could do
something like the code below. (You should actually put it directly in your html template
so that you don't have to use `|safe`)

```python
def foo(request):
    ...
    whois = whois21.WHOIS(domain_name)
    
    whois_data = f"""
    Domain Name: {whois_data.domain}<br>
    Registrar: {', '.join(whois_data.registrar_name)}<br>
    Creation Date: {whois_data.creation_date}<br>
    Expiration Date: {whois_data.expires_date}<br>
    Name Servers: {', '.join(whois_data.name_servers)}<br>
    Status: {whois_data.status}<br>
    Emails: {', '.join(whois_data.emails)}<br>
    Updated Date: {whois_data.updated_date}<br>
    """

    return render(request, 'toolbox/whois.html', { 'whois' : whois_data })
```

Additional Note: Make sure you're using the latest version:
```bash
$ python -m pip install -U whois21
```

**Comment by Hugz59** [comment]
Hey ! 

Oh thanks you save my life ! 

I didn't think to use the <pre> tag. 

I wanted to return all datas of the whois. It's working now. 

Thank you very much !
